<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            // ════════════════════════════════════════════════════════════
            // ACADEMICS
            // ════════════════════════════════════════════════════════════
            [
                'name'             => 'Curriculum',
                'slug'             => 'curriculum',
                'content'          => '<h2>Our Curriculum</h2><p>HS Global Academy follows the <strong>CBSE (Central Board of Secondary Education)</strong> curriculum, designed to foster holistic development through a balanced blend of academics, co-curricular activities, and life skills.</p><h3>Pre-Primary (Nursery – UKG)</h3><p>Activity-based learning with focus on motor skills, phonics, number readiness, and social interaction through play-way methods.</p><h3>Primary (Class I – V)</h3><p>Foundation-building across languages, mathematics, environmental studies, computer science, and value education. Emphasis on reading habits and conceptual clarity.</p><h3>Middle (Class VI – VIII)</h3><p>Introduction of specialized subjects with project-based and experiential learning. Students explore science, social science, languages, and information technology in depth.</p><h3>Secondary &amp; Senior Secondary (Class IX – XII)</h3><p>Rigorous academic preparation for board examinations with streams in <strong>Science (PCM/PCB)</strong> and <strong>Commerce</strong>. Regular tests, remedial classes, and career guidance prepare students for competitive exams like JEE, NEET, and CUET.</p><h3>Co-Scholastic Areas</h3><ul><li>Art &amp; Craft</li><li>Music (Vocal &amp; Instrumental)</li><li>Dance</li><li>Physical Education &amp; Yoga</li><li>Life Skills &amp; Value Education</li></ul>',
                'image'            => 'static/background/main.jpeg',
                'file'             => null,
                'meta_title'       => 'Curriculum - HS Global Academy',
                'meta_description' => 'Explore the CBSE curriculum at HS Global Academy from pre-primary to senior secondary, including co-scholastic areas.',
                'meta_keywords'    => 'CBSE curriculum, academics, HS Global Academy, pre-primary, primary, secondary, senior secondary',
                'is_published'     => true,
            ],
            [
                'name'             => 'Examination Policy',
                'slug'             => 'examination-policy',
                'content'          => '<h2>Examination Policy</h2><p>HS Global Academy follows a <strong>Continuous and Comprehensive Evaluation (CCE)</strong> pattern as prescribed by CBSE, ensuring regular assessment of both scholastic and co-scholastic areas.</p><h3>Assessment Structure</h3><table><thead><tr><th>Term</th><th>Type</th><th>Weightage</th></tr></thead><tbody><tr><td>Term I (April – September)</td><td>Periodic Test 1 + Half-Yearly Exam</td><td>50%</td></tr><tr><td>Term II (October – March)</td><td>Periodic Test 2 + Annual Exam</td><td>50%</td></tr></tbody></table><h3>Key Policies</h3><ul><li>Minimum <strong>75% attendance</strong> is mandatory to appear in examinations.</li><li>Periodic Tests are conducted for <strong>40 marks</strong>; Half-Yearly and Annual Exams for <strong>80 marks</strong>.</li><li>Internal assessment (20 marks) includes notebook submission, subject enrichment activities, and practicals.</li><li>Students absent during exams must produce a <strong>medical certificate</strong> and may be eligible for a retest at the school\'s discretion.</li><li>Results are communicated through <strong>Report Cards</strong> during Parent-Teacher Meetings (PTMs).</li></ul><h3>Promotion Policy</h3><p>Promotion is based on cumulative performance across both terms. Students must score a minimum of <strong>33%</strong> in each subject to qualify for promotion to the next class.</p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Examination Policy - HS Global Academy',
                'meta_description' => 'Understand the CBSE CCE examination pattern, assessment structure, and promotion policy at HS Global Academy.',
                'meta_keywords'    => 'examination policy, CBSE CCE, assessment, promotion policy, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'School Timing',
                'slug'             => 'school-timing',
                'content'          => '<h2>School Timing</h2><p>HS Global Academy operates with well-structured schedules to maximize learning while ensuring students have adequate time for rest and recreation.</p><h3>Regular School Hours</h3><table><thead><tr><th>Session</th><th>Timing</th></tr></thead><tbody><tr><td>Pre-Primary (Nursery – UKG)</td><td>8:30 AM – 12:30 PM</td></tr><tr><td>Primary &amp; Middle (Class I – VIII)</td><td>8:30 AM – 2:30 PM</td></tr><tr><td>Secondary &amp; Sr. Secondary (Class IX – XII)</td><td>8:30 AM – 3:00 PM</td></tr></tbody></table><h3>Daily Routine Highlights</h3><ul><li><strong>Morning Assembly:</strong> 8:30 AM – 8:50 AM (Prayer, Thought of the Day, News, National Anthem)</li><li><strong>Zero Period (IX–XII):</strong> 8:50 AM – 9:30 AM (Remedial / Enrichment Classes)</li><li><strong>Lunch Break:</strong> 12:00 PM – 12:30 PM</li><li><strong>Dispersal:</strong> As per class schedule</li></ul><h3>Office Hours</h3><ul><li><strong>Principal Office:</strong> 9:00 AM – 11:00 AM (With prior appointment)</li><li><strong>Administrative Office:</strong> 8:30 AM – 2:00 PM (Monday – Saturday)</li><li><strong>Fee Counter:</strong> 9:00 AM – 1:00 PM</li></ul><h3>Visiting Hours for Parents</h3><p>Parents can meet teachers on <strong>2nd and 4th Saturday</strong> of every month between <strong>10:00 AM – 12:00 PM</strong>, or during scheduled PTMs.</p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'School Timing - HS Global Academy',
                'meta_description' => 'View the daily school timings, office hours, and parent visiting hours at HS Global Academy.',
                'meta_keywords'    => 'school timing, daily schedule, office hours, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Rules & Regulations',
                'slug'             => 'rules-regulations',
                'content'          => '<h2>Rules &amp; Regulations</h2><p>To maintain discipline and a positive learning atmosphere, HS Global Academy expects all students to follow the school rules diligently.</p><h3>Attendance &amp; Punctuality</h3><ul><li>All students must arrive at school <strong>5 minutes before</strong> the morning assembly.</li><li>Minimum <strong>75% attendance</strong> is mandatory for promotion.</li><li>Leave must be applied for in advance using the <strong>Leave Record</strong> section in the school diary.</li><li>Medical leave exceeding 3 days requires a <strong>doctor\'s certificate</strong>.</li><li>Late arrivals (after 3 warnings) will require a parental explanation.</li></ul><h3>Discipline &amp; Conduct</h3><ul><li>Students must wear the <strong>prescribed uniform</strong> with polished shoes and proper ID card.</li><li>Use of <strong>mobile phones, smartwatches, cameras, or any electronic gadgets</strong> is strictly prohibited on campus.</li><li>Students must maintain <strong>silence in corridors, library, and labs</strong>.</li><li>Bullying, ragging, use of foul language, or any form of misbehavior will attract <strong>strict disciplinary action</strong> including suspension.</li><li>Damaging school property will result in a <strong>fine</strong> equivalent to the cost of repair/replacement.</li></ul><h3>Academic Integrity</h3><ul><li>Malpractice during exams will lead to <strong>cancellation of the paper</strong> and disciplinary review.</li><li>Homework and assignments must be submitted on time.</li></ul><h3>General</h3><ul><li>Students must bring the <strong>school diary</strong> daily.</li><li>Valuable items and jewellery are not permitted.</li><li>The school is not responsible for loss of personal belongings.</li></ul>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Rules & Regulations - HS Global Academy',
                'meta_description' => 'Read the school rules regarding attendance, discipline, uniform, academic integrity, and general code of conduct.',
                'meta_keywords'    => 'school rules, regulations, discipline, attendance, uniform, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Uniform Regulations',
                'slug'             => 'uniform-regulations',
                'content'          => '<h2>Uniform Regulations</h2><p>The uniform at HS Global Academy instils a sense of identity, equality, and discipline among students. All students must adhere to the uniform code strictly.</p><h3>Boys (All Classes)</h3><table><thead><tr><th>Item</th><th>Specification</th></tr></thead><tbody><tr><td>Shirt</td><td>Half-sleeve, check pattern (school-prescribed), neatly tucked in</td></tr><tr><td>Trousers</td><td>Navy blue (grey for Sr. Secondary), well-fitted</td></tr><tr><td>Socks</td><td>Navy blue with school stripe</td></tr><tr><td>Shoes</td><td>Black leather, lace-up (formal)</td></tr><tr><td>Belt</td><td>Black leather with plain buckle</td></tr><tr><td>ID Card</td><td>Must be worn at all times on campus</td></tr></tbody></table><h3>Girls (All Classes)</h3><table><thead><tr><th>Item</th><th>Specification</th></tr></thead><tbody><tr><td>Shirt</td><td>Half-sleeve, check pattern (school-prescribed)</td></tr><tr><td>Skirt / Salwar</td><td>Navy blue, knee-length (skirt for primary, salwar for middle &amp; above)</td></tr><tr><td>Dupatta</td><td>Navy blue (Class VI onwards)</td></tr><tr><td>Socks</td><td>Navy blue with school stripe</td></tr><tr><td>Shoes</td><td>Black leather, lace-up (formal)</td></tr><tr><td>ID Card</td><td>Must be worn at all times on campus</td></tr></tbody></table><h3>House Dress (Every Wednesday &amp; Saturday)</h3><ul><li>House-coloured T-shirt (Red – Shivaji House, Blue – Tagore House, Green – Raman House, Yellow – Ashoka House)</li><li>White trousers/skirt and white shoes with white socks</li></ul><h3>Winter Uniform (November – February)</h3><ul><li>Navy blue blazer (with school monogram)</li><li>Navy blue V-neck sweater</li></ul><h3>Important Notes</h3><ul><li>Uniform must be <strong>clean and neatly ironed</strong> every day.</li><li>Hair must be well-groomed — boys: short and neat; girls (long hair): neatly plaited.</li><li>Nail polish and mehendi are not allowed.</li><li>Sports uniform is mandatory for Physical Education periods.</li></ul>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Uniform Regulations - HS Global Academy',
                'meta_description' => 'Complete uniform code for boys and girls at HS Global Academy including summer, winter, and house dress regulations.',
                'meta_keywords'    => 'uniform regulations, school dress code, HS Global Academy, uniform rules',
                'is_published'     => true,
            ],
            [
                'name'             => 'Book List',
                'slug'             => 'book-list',
                'content'          => '<h2>Book List &amp; Stationery</h2><p>The following books and stationery items are required for each class. All books are in accordance with the <strong>NCERT / CBSE syllabus</strong> and are available at the school book store or authorized vendors.</p><h3>Nursery – UKG</h3><ul><li>English Primer (Publisher: Scholar)</li><li>Maths Primer (Publisher: Scholar)</li><li>Hindi Primer (Publisher: Scholar)</li><li>Art &amp; Craft Book</li><li>4-line notebook (x2), Square-line notebook (x1), Drawing notebook (x1)</li></ul><h3>Class I – V</h3><table><thead><tr><th>Subject</th><th>Book Title / Publisher</th></tr></thead><tbody><tr><td>English</td><td>Marigold – NCERT</td></tr><tr><td>Mathematics</td><td>Math Magic – NCERT</td></tr><tr><td>EVS</td><td>Looking Around – NCERT</td></tr><tr><td>Hindi</td><td>Rimjhim – NCERT</td></tr><tr><td>Computer</td><td>IT Beans – KIPS Publishing</td></tr><tr><td>GK</td><td>Know for Sure – Britannica</td></tr></tbody></table><p><em>Single-line notebooks: English (x2), Maths (x2), Hindi (x2), EVS (x1), Computer (x1).</em></p><h3>Class VI – VIII</h3><table><thead><tr><th>Subject</th><th>Book Title / Publisher</th></tr></thead><tbody><tr><td>English</td><td>Honeysuckle (VI) / Honeycomb (VII) / Honeydew (VIII) – NCERT</td></tr><tr><td>Maths</td><td>Mathematics – NCERT</td></tr><tr><td>Science</td><td>Science – NCERT</td></tr><tr><td>Social Science</td><td>Our Past, Social &amp; Political Life, Resources – NCERT</td></tr><tr><td>Hindi</td><td>Vasant – NCERT</td></tr><tr><td>Computer</td><td>IT Beans – KIPS Publishing</td></tr><tr><td>Atlas</td><td>School Atlas – Oxford</td></tr></tbody></table><h3>Class IX – X</h3><table><thead><tr><th>Subject</th><th>Book Title / Publisher</th></tr></thead><tbody><tr><td>English</td><td>Beehive &amp; Moments – NCERT</td></tr><tr><td>Maths</td><td>Mathematics – NCERT + R.D. Sharma (Reference)</td></tr><tr><td>Science</td><td>Science – NCERT + S. Chand (Reference)</td></tr><tr><td>Social Science</td><td>India &amp; Contemporary World, Democratic Politics – NCERT</td></tr><tr><td>Hindi</td><td>Sanchayan &amp; Sparsh – NCERT</td></tr></tbody></table><h3>Class XI – XII (Science Stream)</h3><table><thead><tr><th>Subject</th><th>Book Title / Publisher</th></tr></thead><tbody><tr><td>English Core</td><td>Flamingo &amp; Vistas – NCERT</td></tr><tr><td>Physics</td><td>Physics – NCERT + H.C. Verma (Reference)</td></tr><tr><td>Chemistry</td><td>Chemistry – NCERT + O.P. Tandon (Reference)</td></tr><tr><td>Biology / Maths</td><td>Biology – NCERT / Maths – NCERT + R.D. Sharma</td></tr></tbody></table><p><em>Note: The school may update the book list annually. Parents will be notified of any changes before the new academic session begins.</em></p>',
                'image' => null,
                'file'             => 'static/background/main.jpeg',
                'meta_title'       => 'Book List & Stationery - HS Global Academy',
                'meta_description' => 'Complete book list and stationery requirements for all classes at HS Global Academy as per NCERT/CBSE syllabus.',
                'meta_keywords'    => 'book list, NCERT books, CBSE books, stationery, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Fee Structure',
                'slug'             => 'fee-structure',
                'content'          => '<h2>Fee Structure 2026-2027</h2><p>HS Global Academy is committed to providing quality education at an affordable fee. The fee structure is transparent with no hidden charges.</p><h3>One-Time Charges (At Admission)</h3><table><thead><tr><th>Fee Head</th><th>Amount (₹)</th></tr></thead><tbody><tr><td>Registration Fee</td><td>500</td></tr><tr><td>Admission Fee</td><td>5,000</td></tr><tr><td>Caution Money (Refundable)</td><td>3,000</td></tr></tbody></table><h3>Annual Charges (Per Year)</h3><table><thead><tr><th>Fee Head</th><th>Amount (₹)</th></tr></thead><tbody><tr><td>Annual Composite Fee</td><td>6,000</td></tr><tr><td>Examination Fee</td><td>1,500</td></tr></tbody></table><h3>Monthly Tuition Fee</h3><table><thead><tr><th>Class</th><th>Tuition Fee (₹ / Month)</th></tr></thead><tbody><tr><td>Nursery – UKG</td><td>1,200</td></tr><tr><td>Class I – V</td><td>1,600</td></tr><tr><td>Class VI – VIII</td><td>2,000</td></tr><tr><td>Class IX – X</td><td>2,400</td></tr><tr><td>Class XI – XII (Science)</td><td>2,800</td></tr><tr><td>Class XI – XII (Commerce)</td><td>2,600</td></tr></tbody></table><h3>Payment Guidelines</h3><ul><li>Monthly tuition fee is payable by the <strong>10th of every month</strong>.</li><li>Late payment attracts a fine of <strong>₹50 per day</strong>.</li><li>Annual charges are payable in two instalments: <strong>April and October</strong>.</li><li>Fees can be paid via <strong>cash, cheque, UPI, or online transfer</strong>.</li><li>Name of the student, class, and father\'s name must be mentioned in all payment references.</li></ul><h3>Concessions</h3><ul><li><strong>Sibling Concession:</strong> 10% discount on tuition fee for the second child, 15% for the third.</li><li><strong>Merit-Based Concession:</strong> Students scoring 90%+ in board exams may receive a tuition fee waiver of up to 25% (subject to management approval).</li></ul><h3>Refund Policy</h3><p>Caution money is refundable upon withdrawal, subject to clearance of all dues. Admission and registration fees are <strong>non-refundable</strong>.</p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Fee Structure 2026-2027 - HS Global Academy',
                'meta_description' => 'Complete fee structure for all classes at HS Global Academy including tuition, annual charges, concessions, and payment guidelines.',
                'meta_keywords'    => 'fee structure, tuition fees, school fees, annual charges, HS Global Academy',
                'is_published'     => true,
            ],

            // ════════════════════════════════════════════════════════════
            // ADMISSION
            // ════════════════════════════════════════════════════════════
            [
                'name'             => 'Admission Procedure',
                'slug'             => 'admission-procedure',
                'content'          => '<h2>Admission Procedure</h2><p>HS Global Academy welcomes applications from all students irrespective of caste, creed, or religion. The admission process is <strong>transparent, merit-based, and inclusive</strong>.</p><h3>Step-by-Step Process</h3><ol><li><strong>Registration</strong><br>Fill the <strong>online enquiry form</strong> or visit the school office to collect the prospectus and registration form. Registration fee: ₹500 (non-refundable).</li><li><strong>Submission of Documents</strong><br>Submit the completed registration form along with required documents (see Documents Required section).</li><li><strong>Entrance Assessment</strong> (Class I onwards)<br>A written assessment in English, Maths, and General Awareness. Duration: 60-90 minutes depending on the class.</li><li><strong>Interaction with Parents &amp; Student</strong><br>Selected candidates and their parents are invited for an informal interaction with the Principal / Admission Committee.</li><li><strong>Confirmation of Admission</strong><br>Upon selection, pay the admission fee and caution money within <strong>7 working days</strong> to secure the seat.</li></ol><h3>Age Criteria (As on 1st April of the academic year)</h3><table><thead><tr><th>Class</th><th>Minimum Age</th></tr></thead><tbody><tr><td>Nursery</td><td>3+ years</td></tr><tr><td>LKG</td><td>4+ years</td></tr><tr><td>UKG</td><td>5+ years</td></tr><tr><td>Class I</td><td>6+ years</td></tr></tbody></table><h3>Important Notes</h3><ul><li>Admissions are open from <strong>January to August</strong>, subject to availability of seats.</li><li>Mid-session admissions are considered on a case-by-case basis.</li><li>The school reserves the right to accept or reject any application without assigning a reason.</li></ul>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Admission Procedure - HS Global Academy',
                'meta_description' => 'Step-by-step admission procedure at HS Global Academy including registration, entrance assessment, and age criteria.',
                'meta_keywords'    => 'admission procedure, school admission, registration, age criteria, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Eligibility Criteria',
                'slug'             => 'eligibility-criteria',
                'content'          => '<h2>Eligibility Criteria</h2><p>To ensure a smooth academic journey, HS Global Academy has defined clear eligibility criteria for each stage of admission.</p><h3>Age Eligibility</h3><table><thead><tr><th>Class</th><th>Age as on 1st April</th></tr></thead><tbody><tr><td>Nursery</td><td>3 years to 4 years</td></tr><tr><td>LKG</td><td>4 years to 5 years</td></tr><tr><td>UKG</td><td>5 years to 6 years</td></tr><tr><td>Class I</td><td>6 years to 7 years</td></tr><tr><td>Class II onwards</td><td>As per previous class pass certificate</td></tr></tbody></table><h3>Academic Eligibility</h3><ul><li>For <strong>Class I – VIII</strong>: No prior entrance test. Admission is based on age eligibility, document verification, and an informal interaction.</li><li>For <strong>Class IX</strong>: Transfer Certificate from a recognized school + Written Assessment in English, Maths, and Science.</li><li>For <strong>Class XI (Science)</strong>: Minimum <strong>60% aggregate</strong> in Class X with at least 60% in Science and Maths.</li><li>For <strong>Class XI (Commerce)</strong>: Minimum <strong>50% aggregate</strong> in Class X.</li></ul><h3>Documents Required at Time of Admission</h3><ul><li>Birth Certificate (original + photocopy)</li><li>Transfer Certificate (Class II onwards)</li><li>Previous Class Report Card / Marksheet</li><li>4 Passport-size photographs</li><li>2 Passport-size photographs of each parent</li><li>Aadhaar Card of student and parents (photocopy)</li><li>Address Proof (photocopy)</li><li>Medical Fitness Certificate</li></ul><h3>Reservation</h3><p>As per the Right to Education (RTE) Act, <strong>25% seats</strong> in entry-level classes (Nursery, LKG, Class I) are reserved for students from economically weaker sections (EWS) and disadvantaged groups. RTE admissions are governed by norms set by the District Education Office.</p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Eligibility Criteria - HS Global Academy',
                'meta_description' => 'Age criteria, academic requirements, and document checklist for admission at HS Global Academy.',
                'meta_keywords'    => 'eligibility criteria, age criteria, admission requirements, HS Global Academy, RTE',
                'is_published'     => true,
            ],
            [
                'name'             => 'Documents Required',
                'slug'             => 'documents-required',
                'content'          => '<h2>Documents Required</h2><p>To complete the admission process at HS Global Academy, the following documents must be submitted. Incomplete applications will not be processed.</p><h3>Mandatory Documents Checklist</h3><table><thead><tr><th>#</th><th>Document</th><th>Copies Required</th><th>Remarks</th></tr></thead><tbody><tr><td>1</td><td>Birth Certificate</td><td>1 Original + 1 Photocopy</td><td>Issued by Municipal Corporation / Hospital</td></tr><tr><td>2</td><td>Transfer Certificate (TC)</td><td>1 Original</td><td>From previous school (Class II onwards)</td></tr><tr><td>3</td><td>Previous Class Marksheet / Report Card</td><td>1 Photocopy</td><td>Duly attested</td></tr><tr><td>4</td><td>Passport-size Photographs (Student)</td><td>4</td><td>Recent, colour</td></tr><tr><td>5</td><td>Passport-size Photographs (Parents)</td><td>2 each</td><td>Recent, colour</td></tr><tr><td>6</td><td>Aadhaar Card (Student)</td><td>1 Photocopy</td><td>Self-attested</td></tr><tr><td>7</td><td>Aadhaar Card (Parents)</td><td>1 Photocopy each</td><td>Self-attested</td></tr><tr><td>8</td><td>Address Proof</td><td>1 Photocopy</td><td>Aadhaar / Ration Card / Passport / Utility Bill</td></tr><tr><td>9</td><td>Medical Fitness Certificate</td><td>1 Original</td><td>From a registered MBBS doctor</td></tr><tr><td>10</td><td>Blood Group Report</td><td>1 Photocopy</td><td>Optional but recommended</td></tr><tr><td>11</td><td>Caste Certificate</td><td>1 Photocopy</td><td>If applicable (SC/ST/OBC/EWS)</td></tr><tr><td>12</td><td>Income Certificate</td><td>1 Photocopy</td><td>For EWS / RTE admission</td></tr></tbody></table><h3>Additional Documents (If Applicable)</h3><ul><li><strong>Migration Certificate:</strong> Required for students migrating from a different state board to CBSE (Class X onwards).</li><li><strong>Disability Certificate:</strong> For students requiring special assistance or accommodations.</li><li><strong>Single Parent / Guardian Affidavit:</strong> If applicable.</li></ul><h3>Important Instructions</h3><ul><li>All photocopies must be <strong>self-attested</strong> by the parent/guardian.</li><li>Original documents will be returned after verification.</li><li>The school reserves the right to <strong>cancel admission</strong> if any document is found to be falsified.</li></ul>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Documents Required for Admission - HS Global Academy',
                'meta_description' => 'Complete checklist of documents required for school admission at HS Global Academy with submission instructions.',
                'meta_keywords'    => 'admission documents, required documents, document checklist, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Fee Payment Rules',
                'slug'             => 'fee-payment-rules',
                'content'          => '<h2>Fee Payment Rules</h2><p>HS Global Academy follows a structured fee payment system to ensure transparency and convenience for all parents and guardians.</p><h3>Payment Schedule</h3><table><thead><tr><th>Fee Type</th><th>Due Date / Frequency</th><th>Mode</th></tr></thead><tbody><tr><td>Admission Fee + Caution Money</td><td>At the time of admission</td><td>Cash / Cheque / UPI / NEFT</td></tr><tr><td>Annual Composite Fee</td><td>April (1st Instalment) &amp; October (2nd Instalment)</td><td>Cash / Cheque / UPI / NEFT</td></tr><tr><td>Monthly Tuition Fee</td><td>By 10th of every month</td><td>Cash / Cheque / UPI / NEFT</td></tr></tbody></table><h3>Payment Methods</h3><ul><li><strong>Cash:</strong> At the school fee counter between 9:00 AM – 1:00 PM on working days.</li><li><strong>Cheque / Demand Draft:</strong> In favour of <strong>"HS Global Academy"</strong>, payable at the school\'s city branch.</li><li><strong>UPI / QR Code:</strong> Scan the QR code available at the fee counter or school website.</li><li><strong>NEFT / Bank Transfer:</strong><br>Bank: State Bank of India<br>A/C Name: HS Global Academy<br>A/C No: XXXXXXXXXX<br>IFSC: SBIN000XXXX</li></ul><h3>Late Payment Policy</h3><ul><li>A late fee of <strong>₹50 per day</strong> is applicable after the 10th of the month.</li><li>If fees remain unpaid for <strong>two consecutive months</strong>, the student\'s name may be struck off the rolls.</li><li>Re-admission (if approved) will require payment of <strong>all outstanding dues + re-admission fee of ₹2,000</strong>.</li></ul><h3>Fee Receipt</h3><ul><li>A computer-generated fee receipt is issued for every payment.</li><li>Parents must retain receipts for the entire academic year for record purposes.</li><li>Duplicate receipts can be obtained from the accounts office on written request (₹50 fee).</li></ul><h3>Additional Charges</h3><ul><li>Transport fee: ₹800 – ₹1,500 per month (depending on route/distance).</li><li>Examination fee for board classes (X &amp; XII): As per CBSE norms (separately intimated).</li><li>Practical / Lab fee for Science stream (XI–XII): ₹500 per subject per year.</li></ul><h3>Refund &amp; Withdrawal</h3><p>One month\'s written notice or one month\'s tuition fee in lieu of notice is required for withdrawal. Caution money is refunded after clearance of all dues and library/lab items.</p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Fee Payment Rules - HS Global Academy',
                'meta_description' => 'Complete fee payment guidelines including schedule, payment methods, late fee policy, and refund rules at HS Global Academy.',
                'meta_keywords'    => 'fee payment, payment rules, late fee, refund policy, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'Withdrawal / Transfer',
                'slug'             => 'withdrawal-transfer',
                'content'          => '<h2>Withdrawal &amp; Transfer</h2><p>HS Global Academy has a clear and fair withdrawal and transfer policy to assist families during transitions.</p><h3>Withdrawal Procedure</h3><ol><li>Submit a <strong>written application</strong> for withdrawal, signed by both parents/guardians, addressed to the Principal.</li><li>Provide <strong>one month\'s notice</strong> or pay one month\'s tuition fee in lieu of notice.</li><li>Clear all outstanding dues — tuition fee, library fines, lab charges, transport fee, and any other pending payments.</li><li>Return all school property — library books, lab equipment, sports gear, etc.</li><li>Collect the <strong>Transfer Certificate (TC)</strong> and original documents after 7 working days of submitting the application.</li></ol><h3>Transfer Certificate (TC)</h3><ul><li>The TC is issued <strong>free of cost</strong> if all dues are cleared.</li><li>A <strong>duplicate TC</strong> can be issued on written request with an affidavit and a fee of ₹500.</li><li>TC contains the student\'s personal details, dates of enrollment and withdrawal, class last attended, and a character / conduct summary.</li></ul><h3>Mid-Session Withdrawal</h3><ul><li>Parents withdrawing a student mid-session must pay the <strong>full session fee</strong> up to the quarter of withdrawal.</li><li>Caution money is refunded after deducting any outstanding amounts.</li></ul><h3>Transfer Within CBSE Schools</h3><ul><li>For students transferring to another CBSE-affiliated school, the TC and previous class marksheets are sufficient.</li><li>A <strong>Migration Certificate</strong> is additionally required for students transferring to a different board (State Board, ICSE, IB, etc.).</li></ul><h3>Refund Timeline</h3><table><thead><tr><th>Item</th><th>Refundable?</th><th>Timeline</th></tr></thead><tbody><tr><td>Caution Money</td><td>Yes</td><td>Within 30 days after clearance</td></tr><tr><td>Admission Fee</td><td>No</td><td>—</td></tr><tr><td>Annual Charges</td><td>Pro-rated (if withdrawn in Q1)</td><td>Within 45 days</td></tr><tr><td>Tuition Fee (Advance)</td><td>Yes (adjustable against dues)</td><td>Within 30 days</td></tr></tbody></table><p><em>Note: The school management reserves the right to refuse a TC if the student has been involved in serious disciplinary violations pending investigation.</em></p>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Withdrawal & Transfer Policy - HS Global Academy',
                'meta_description' => 'Complete withdrawal procedure, transfer certificate issuance, and refund policy at HS Global Academy.',
                'meta_keywords'    => 'withdrawal policy, transfer certificate, TC, school leaving, HS Global Academy',
                'is_published'     => true,
            ],
            [
                'name'             => 'TC Sample',
                'slug'             => 'tc-sample',
                'content'          => '<h2>Transfer Certificate – Sample Format</h2><p>Below is the official format of the Transfer Certificate (TC) issued by HS Global Academy. This is for reference purposes only.</p><div style="border:2px solid #000; padding:30px; max-width:700px; margin:0 auto; font-family:serif;"><div style="text-align:center;"><h3 style="margin-bottom:0;">HS GLOBAL ACADEMY</h3><p style="margin-top:0;">Affiliated to CBSE, New Delhi | Affiliation No: XXXXXX</p><p>School Address Line 1, City, State – PIN</p><hr style="border-color:#000;"><h3 style="letter-spacing:4px;">TRANSFER CERTIFICATE</h3></div><p><strong>TC No.:</strong> _______________ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Date:</strong> _______________</p><p><strong>Admission No.:</strong> _______________ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>UID:</strong> _______________</p><hr><p>This is to certify that <strong>____________________________</strong>, Son / Daughter of <strong>Shri / Smt. ____________________________</strong>, Date of Birth: <strong>_______________</strong>, was a bonafide student of this school.</p><table style="width:100%;"><tr><td><strong>Date of Admission:</strong> _____________</td><td><strong>Class at Admission:</strong> __________</td></tr><tr><td><strong>Date of Leaving:</strong> _____________</td><td><strong>Class Last Attended:</strong> __________</td></tr><tr><td><strong>Academic Year:</strong> _____________</td><td><strong>Result:</strong> Passed / Promoted to Class _______</td></tr></table><p><strong>Conduct:</strong> _______________ &nbsp;&nbsp;&nbsp; <strong>Games / Sports Participated:</strong> _______________</p><p><strong>Reason for Leaving:</strong> _______________</p><p><strong>Remarks (if any):</strong> _______________</p><br><table style="width:100%;"><tr><td style="text-align:center;"><strong>_________________________</strong><br>Class Teacher</td><td style="text-align:center;"><strong>_________________________</strong><br>Principal</td></tr></table><br><p style="text-align:center;">(School Seal)</p></div><h3>Important Information</h3><ul><li>The actual TC is printed on the <strong>school\'s official letterhead</strong> with security features.</li><li>A TC is issued only after <strong>full clearance of all dues</strong> and return of school property.</li><li>The TC is a <strong>legal document</strong> — any tampering or falsification is punishable under applicable laws.</li><li>For duplicate TC, submit a written application along with an <strong>affidavit</strong> and ₹500 fee.</li></ul>',
                'image' => null,
                'file' => null,
                'meta_title'       => 'Transfer Certificate Sample - HS Global Academy',
                'meta_description' => 'View the official Transfer Certificate (TC) sample format issued by HS Global Academy.',
                'meta_keywords'    => 'TC sample, transfer certificate format, school leaving certificate, HS Global Academy',
                'is_published'     => true,
            ],
        ];

        foreach ($pages as $page) {
            Page::create($page);
        }
    }
}
